#APPLICATION-PROPERTIES
server:
  address: localhost
  port: 7070
  context-path: /crud_jpa_elastic
  
spring:
  data:
    elasticsearch:
#      cluster-nodes: localhost:9300
      cluster-name: escluster
      repositories:
        enabled: true
      properties:
        path.home: E:/elastic_search_db
        transport.tcp.connect_timeout : 120s
---
#DBCONNECTION-PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://localdocker:3306/hibernatecomplete?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
 